# Generated by Django 3.1.4 on 2020-12-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', related_query_name='category', to='blog.category', verbose_name='root_category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('draft', models.BooleanField(db_index=True, default=True, verbose_name='draft')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='publish_time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='posts', to='blog.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['published_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.BooleanField(default=True, verbose_name='comment')),
                ('author', models.BooleanField(default=True, verbose_name='author')),
                ('allow_discussion', models.BooleanField(default=True, verbose_name='allow_discuss')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=True, null=True, verbose_name='content')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='confirm')),
                ('situation', models.BooleanField(default=True, verbose_name='situation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', related_query_name='comment', to='blog.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.BooleanField(default=True, verbose_name='situation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', related_query_name='comment_like', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('comment', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment', verbose_name='comment')),
            ],
            options={
                'verbose_name': 'comment_like',
                'verbose_name_plural': 'comment_likes',
                'unique_together': {('author', 'comment')},
            },
        ),
    ]
