# Generated by Django 3.1.4 on 2021-01-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210116_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsetting',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='blog.post', verbose_name='post'),
        ),
    ]
